language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

env:
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*

matrix:
    allow_failures:
      - env: SYMFONY_VERSION=dev-master
      - php: hhvm
    include:
      - php: 5.5
        env: SYMFONY_VERSION=2.1.*
      - php: 5.5
        env: SYMFONY_VERSION=2.2.*
      - php: 5.5
        env: SYMFONY_VERSION=2.3.*
      - php: 5.5
        env: SYMFONY_VERSION=2.4.*
      - php: 5.5
        env: SYMFONY_VERSION=2.5.*
      - php: 5.5
        env: SYMFONY_VERSION=2.6.*
      - php: 5.5
        env: SYMFONY_VERSION=2.7.*
      - php: 5.4
        env: SYMFONY_VERSION=2.8.*
      - php: 5.5
        env: SYMFONY_VERSION=dev-master
      - php: 7.1
        env: SYMFONY_VERSION=4.0.*@beta

before_script:
    - composer self-update
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer update

script:
    - phpunit --coverage-text
